name: Build Dependencies
permissions:
  contents: write
# Controls when the workflow will run
on:
  # Run On Time
  #schedule:
  #  - cron: '0 0,12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Download and Build
        run: |
          wget -O ghclone.jar https://vitekform.github.io/assets/builder/GHCloner-1.0-fat.jar
          echo Checking java version...
          java -version
          echo Starting app
          java -jar GHCloner-1.0-fat.jar run
          cd working
          cd oraxen
          git init
          ./gradlew build
          cd ..
          cd ..
          java -jar GHCloner-1.0-fat.jar moveBuild
          echo Done!


# Runs a set of commands using the runners shell
