name: Build Dependencies
permissions:
  contents: write
# Controls when the workflow will run
on:
  # Run On Time
  #schedule:
  #  - cron: '0 0,12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Download Oraxen Repo
        run: |
          java -version
          mkdir working
          cd working
          git clone https://github.com/oraxen/Oraxen
          cd Oraxen
          gradle build
          cd build
          git add -f libs
          git commit -m "Build of Oraxen"
      # Runs a set of commands using the runners shell
