# This is a basic workflow to help you get started with Actions

name: Update
permissions:
  contents: write
# Controls when the workflow will run
on:
  # Run On Time
  schedule:
    - cron: '0 0,12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Download PAPI Repo
        run: |
          mkdir papi
          cd papi
          git clone https://github.com/PlaceholderAPI/PlaceholderAPI
          cd PlaceholderAPI
          gradle build
          cd build
          git config --global user.email "vitekform@users.noreply.github.com"
          git config --global user.name "vitekform"
          git remote add origin https://{username}:{password}@github.com/{username}/vitekform.github.io.git
          git add -f libs
          git commit -am "Update of PAPI"
          git push
      # Runs a set of commands using the runners shell
